version: "2.0"

volumes: 
  node_modules: {}
  node_global: {}
  gatsby_cache: {}

services: 
  
  app: 
    environment: 
      - npm_config_fetch_retries=5
      - npm_config_fetch_retry_factor=5
      - npm_config_fetch_retry_mintimeout=50000
      - npm_config_fetch_retry_maxtimeout=250000
    build:
        context: ./
        dockerfile: ./app/Dockerfile
        args: 
          - VERSION=2.9.11

    volumes:
        - ./:/app
        - node_global:/app/.node_modules
        - node_modules:/app/node_modules
        - gatsby_cache:/app/.cache

    ports: 
        - "${PORT}:8005"

    command: ["gatsby", "develop", "--host", "0.0.0.0", "--port", "$PORT"]
