---
new_page_extension: md
auto_deploy: false
admin_path: ".admin"
webhook_url: 
sections:
- type: heading
  label: Pages
- type: directory
  path: src/pages
  label: src/pages
  create: all
  match: "**/*"
  new_doc_ext: mdx
- type: heading
  label: Posts
- type: directory
  path: content/posts
  label: content/posts
  create: all
  match: "**/*"
  templates:
  - programming-post
- type: directory
  path: src/data/posts
  label: src/data/posts
  create: all
  match: "**/*"
  templates:
  - programming-post
- type: heading
  label: Documentation
- type: heading
  label: Templates
- type: document
  path: src/templates/PostTemplate.js
  label: postTemplate
- type: heading
  label: Data
- type: directory
  path: content/data
  label: json
  create: all
  match: "**/*.json"
  new_doc_ext: json
- type: directory
  path: src/data
  label: yaml
  create: all
  match: "*.yaml"
  new_doc_ext: yaml
upload_dir: content/images
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:-:month:-:day:-:filename:"
