name: build gatsby

on: 
  push:
    branches:
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: deploy
        run: yarn gh-pages
