on: 
  push:
    branch:
      - develop      
name: build gatsby
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: yarn install

      - name: replace crappy file
        run: cp ./app/Seo.tpl.js ./node_modules/gatsby-theme-docz/templates/Seo.tpl.js

      - name: build
        env:
            GH_API_KEY: ${{ secrets.GITHUB_API_KEY }}
        run: yarn build

      - name: deploy
        run: yarn gh-pages:ci
        env:
            GH_API_KEY: ${{ secrets.GITHUB_TOKEN }}

