on: 
  push:
    branchs:
      - develop      
name: build gatsby
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: yarn install

      # - name: replace crappy file
      #   run: cp ./app/Seo.tpl.js ./node_modules/gatsby-theme-docz/templates/Seo.tpl.js

      - name: build
        env:
            GH_API_KEY: ${{ secrets.GITHUB_API_KEY }}
        run: yarn build

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        # run: yarn gh-pages:ci
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_PAT: ${{ secrets.GITHUB_API_KEY }}
            BUILD_DIR: 'public/'

